backends:
  env:
    type: env
    prefix: MYPROJECT_
  redis_live:
    type: redis
    host: localhost

templates:
  - src: nginx-mysite.conf.j2
    dest: mysite.conf
    owner: nginx
    mode: '0644'
    check_cmd: /usr/sbin/nginx -t -c {{ path }}
    restart_cmd: /usr/sbin/service nginx reload
    vars:  # Optional way of specifying variable source in config instead of the template
      FQDN:
        backend: redis_live
        key: server/fqdn
