backends:
  env:
    type: env
    prefix: MYPROJECT_
  redis_live:
    type: redis
    host: localhost

templates:
  - src: nginx-mysite.conf.j2
    dest: mysite.conf
    owner: nginx
    mode: '0644'
    check_cmd: /usr/sbin/nginx -t -c {{ path }}
    restart_cmd: /usr/sbin/service nginx reload
    vars:  # Optional way of specifying variable source in config instead of the template
      FQDN:
        backend: redis_live
        key: server/fqdn

logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s|%(name)s|%(levelname)s\t%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
  loggers:
    confp:
      level: DEBUG
      handlers:
        - console
      propagate: yes
